/**
 * Rift Function Router
 *
 * File-system based router for serverless functions.
 * Generated by the build pipeline from the rift/functions/ directory.
 *
 * Route patterns:
 *   rift/functions/api/hello.ts      → /api/hello
 *   rift/functions/api/users/[id].ts → /api/users/:id
 *   rift/functions/index.ts          → /
 *
 * This file is generated — do not edit manually.
 */

// RIFT_ROUTES_PLACEHOLDER will be replaced by the build pipeline
// with the actual route definitions.
const routes: Array<{
  pattern: URLPattern;
  path: string;
  module: () => Promise<{ default: { fetch: (req: Request) => Response | Promise<Response> } } | { fetch: (req: Request) => Response | Promise<Response> }>;
}> = RIFT_ROUTES_PLACEHOLDER;

function resolveHandler(mod: Record<string, unknown>): ((req: Request) => Response | Promise<Response>) | null {
  const d = mod.default as Record<string, unknown> | ((...args: unknown[]) => unknown) | undefined;
  if (d && typeof (d as Record<string, unknown>).fetch === "function") {
    return (d as Record<string, unknown>).fetch as (req: Request) => Response | Promise<Response>;
  }
  if (typeof d === "function") {
    return d as (req: Request) => Response | Promise<Response>;
  }
  if (typeof mod.fetch === "function") {
    return mod.fetch as (req: Request) => Response | Promise<Response>;
  }
  if (typeof mod.handler === "function") {
    return mod.handler as (req: Request) => Response | Promise<Response>;
  }
  return null;
}

export default {
  async fetch(req: Request): Promise<Response> {
    const url = new URL(req.url);

    for (const route of routes) {
      const match = route.pattern.exec(url);
      if (match) {
        // Inject path params as headers
        const groups = match.pathname.groups;
        const enrichedReq = new Request(req.url, {
          method: req.method,
          headers: new Headers([
            ...Array.from(req.headers.entries()),
            ...Object.entries(groups)
              .filter(([, v]) => v !== undefined)
              .map(([k, v]) => [`x-rift-param-${k}`, v as string] as [string, string]),
          ]),
          body: req.body,
        });

        try {
          const mod = await route.module();
          const handler = resolveHandler(mod as Record<string, unknown>);
          if (!handler) {
            return new Response(
              JSON.stringify({ error: `No handler found in ${route.path}` }),
              { status: 500, headers: { "content-type": "application/json" } },
            );
          }
          return await handler(enrichedReq);
        } catch (e) {
          console.error(`[rift-functions] Error in ${route.path}: ${e}`);
          return new Response(
            JSON.stringify({ error: "Internal Server Error" }),
            { status: 500, headers: { "content-type": "application/json" } },
          );
        }
      }
    }

    return new Response(
      JSON.stringify({ error: "Not Found" }),
      { status: 404, headers: { "content-type": "application/json" } },
    );
  },
};
