use std::path::{Path, PathBuf};
use std::process::Stdio;

use rand::Rng;
use tokio::io::{AsyncBufReadExt, BufReader};
use uuid::Uuid;

use crate::{
    db::services as db_services,
    error::AppError,
    ws::{service_broadcast::ServiceLogMessage, ServiceLogBroadcaster},
};

#[derive(Clone)]
pub struct DockerComposeManager {
    pool: sqlx::PgPool,
    service_log_broadcaster: ServiceLogBroadcaster,
    data_dir: PathBuf,
    public_host: String,
    proxy_scheme: String,
    kong_port: u16,
    studio_port: u16,
    db_port: u16,
    posthog_web_port: u16,
    n8n_port: u16,
    affine_port: u16,
}

impl DockerComposeManager {
    pub fn new(
        pool: sqlx::PgPool,
        service_log_broadcaster: ServiceLogBroadcaster,
        data_dir: PathBuf,
        public_host: String,
        proxy_scheme: String,
        kong_port: u16,
        studio_port: u16,
        db_port: u16,
        posthog_web_port: u16,
        n8n_port: u16,
        affine_port: u16,
    ) -> Self {
        Self {
            pool,
            service_log_broadcaster,
            data_dir,
            public_host,
            proxy_scheme,
            kong_port,
            studio_port,
            db_port,
            posthog_web_port,
            n8n_port,
            affine_port,
        }
    }

    pub async fn deploy_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        tokio::fs::create_dir_all(&service_dir)
            .await
            .map_err(|e| AppError::Internal(format!("failed to create service dir: {e}")))?;

        // Update status to deploying
        db_services::update_status(&self.pool, service_id, "deploying", None).await?;

        self.log(service_id, "info", "Generating Supabase configuration...", "system")
            .await?;

        // Generate secrets
        let jwt_secret = generate_random_string(64);
        let postgres_password = generate_random_string(32);
        let dashboard_password = generate_random_string(24);
        let secret_key_base = generate_hex_string(64);
        let anon_key = generate_supabase_jwt(&jwt_secret, "anon");
        let service_role_key = generate_supabase_jwt(&jwt_secret, "service_role");

        self.log(service_id, "info", "Writing environment configuration...", "system")
            .await?;

        // Write .env
        let env_content = format!(
            r#"# Supabase Configuration (auto-generated by Rift)
POSTGRES_PASSWORD={postgres_password}
JWT_SECRET={jwt_secret}
SUPABASE_ANON_KEY={anon_key}
SUPABASE_SERVICE_KEY={service_role_key}
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD={dashboard_password}
SECRET_KEY_BASE={secret_key_base}

POSTGRES_HOST=supabase-db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

KONG_HTTP_PORT={kong_port}
STUDIO_PORT={studio_port}
POSTGRES_EXTERNAL_PORT={db_port}

API_EXTERNAL_URL={scheme}://{public_host}:{kong_port}
SUPABASE_PUBLIC_URL={scheme}://{public_host}:{kong_port}

SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false

STUDIO_DEFAULT_ORGANIZATION=Rift
STUDIO_DEFAULT_PROJECT=Default
"#,
            postgres_password = postgres_password,
            jwt_secret = jwt_secret,
            anon_key = anon_key,
            service_role_key = service_role_key,
            dashboard_password = dashboard_password,
            secret_key_base = secret_key_base,
            scheme = self.proxy_scheme,
            public_host = self.public_host,
            kong_port = self.kong_port,
            studio_port = self.studio_port,
            db_port = self.db_port,
        );

        tokio::fs::write(service_dir.join(".env"), &env_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write .env: {e}")))?;

        self.log(service_id, "info", "Writing Docker Compose manifest...", "system")
            .await?;

        // Write docker-compose.yml
        let compose_content = generate_supabase_compose();
        tokio::fs::write(service_dir.join("docker-compose.yml"), &compose_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write docker-compose.yml: {e}")))?;

        // Write required config files
        self.write_supabase_configs(&service_dir, &anon_key, &service_role_key, &jwt_secret).await?;

        // Remove old DB data so init scripts re-run on fresh deploy
        let db_data_dir = service_dir.join("volumes/db/data");
        if db_data_dir.exists() {
            tokio::fs::remove_dir_all(&db_data_dir).await.ok();
            tokio::fs::create_dir_all(&db_data_dir).await.map_err(|e| {
                AppError::Internal(format!("failed to recreate db data dir: {e}"))
            })?;
        }

        // Pull images
        self.log(service_id, "info", "Pulling Supabase Docker images...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["pull"], service_id)
            .await
        {
            let err_msg = format!("Failed to pull images: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        // Start services
        self.log(service_id, "info", "Starting Supabase services...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["up", "-d"], service_id)
            .await
        {
            let err_msg = format!("Failed to start services: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        // Connect engine container to the service's Docker network so the proxy
        // can reach Supabase containers (kong, studio) by container name.
        // The Supabase DB service is named 'supabase-db' (not 'db') to avoid
        // DNS conflicts with the Rift DB on the engine's default network.
        self.connect_engine_to_service_network(service_id).await;

        // Health check
        self.log(service_id, "info", "Waiting for Supabase to be ready...", "system")
            .await?;

        let healthy = self
            .wait_for_health(service_id, &service_dir, &["supabase-db", "kong", "auth", "realtime", "storage", "meta"])
            .await;

        if healthy {
            // Store connection info.
            // `internal_*_url` use Docker container names reachable from the engine
            // after joining the service network. Kong listens on 8000, Studio on 3000
            // internally. `api_url`/`studio_url` use localhost published ports for
            // direct user access from the VPS host.
            let connection_info = serde_json::json!({
                "api_url": format!("{}://{}:{}", self.proxy_scheme, self.public_host, self.kong_port),
                "studio_url": format!("{}://{}:{}", self.proxy_scheme, self.public_host, self.studio_port),
                "internal_api_url": format!("http://{}-kong-1:8000", service_id),
                "internal_studio_url": format!("http://{}-studio-1:3000", service_id),
                "db_connection_string": format!(
                    "postgresql://postgres:{}@{}:{}/postgres",
                    postgres_password, self.public_host, self.db_port
                ),
                "anon_key": anon_key,
                "service_role_key": service_role_key,
                "dashboard_username": "supabase",
                "dashboard_password": dashboard_password,
            });

            db_services::update_connection_info(&self.pool, service_id, &connection_info).await?;
            db_services::update_status_started(&self.pool, service_id, "running").await?;

            self.log(service_id, "info", "Supabase is ready!", "system")
                .await?;
        } else {
            let err_msg = "Health check timed out — Supabase may still be starting";
            self.log(service_id, "warn", err_msg, "system").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(err_msg)).await?;
        }

        Ok(())
    }

    pub async fn stop_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Stopping Supabase services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["stop"], service_id)
            .await?;

        db_services::update_status_stopped(&self.pool, service_id, "stopped").await?;
        self.log(service_id, "info", "Supabase stopped.", "system")
            .await?;

        Ok(())
    }

    pub async fn start_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Starting Supabase services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["start"], service_id)
            .await?;

        // Re-ensure engine is connected to service network (may have been lost
        // if the engine container was restarted since last deploy).
        self.connect_engine_to_service_network(service_id).await;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "Supabase started.", "system")
            .await?;

        Ok(())
    }

    pub async fn restart_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Restarting Supabase services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["restart"], service_id)
            .await?;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "Supabase restarted.", "system")
            .await?;

        Ok(())
    }

    pub async fn remove_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        db_services::update_status(&self.pool, service_id, "removing", None).await?;

        self.log(service_id, "info", "Removing Supabase services and volumes...", "docker")
            .await?;

        // Ignore errors during removal — service dir may not exist
        let _ = self
            .run_compose_command(&service_dir, &["down", "-v", "--remove-orphans"], service_id)
            .await;

        // Clean up the service directory
        let _ = tokio::fs::remove_dir_all(&service_dir).await;

        self.log(service_id, "info", "Supabase removed.", "system")
            .await?;

        Ok(())
    }

    // ---- PostHog lifecycle ----

    pub async fn deploy_posthog(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        tokio::fs::create_dir_all(&service_dir)
            .await
            .map_err(|e| AppError::Internal(format!("failed to create service dir: {e}")))?;

        db_services::update_status(&self.pool, service_id, "deploying", None).await?;

        self.log(service_id, "info", "Generating PostHog configuration...", "system")
            .await?;

        let secret_key = generate_hex_string(56);
        let encryption_salt = generate_hex_string(32);
        let postgres_password = generate_random_string(32);

        // Clone PostHog repo for ClickHouse config files
        self.log(service_id, "info", "Cloning PostHog repository for config files...", "system")
            .await?;

        let posthog_repo_dir = service_dir.join("posthog");
        if posthog_repo_dir.exists() {
            tokio::fs::remove_dir_all(&posthog_repo_dir).await.ok();
        }

        let clone_output = tokio::process::Command::new("git")
            .args([
                "clone",
                "--depth=1",
                "--filter=blob:none",
                "--sparse",
                "https://github.com/PostHog/posthog.git",
                "posthog",
            ])
            .current_dir(&service_dir)
            .output()
            .await
            .map_err(|e| AppError::Internal(format!("failed to clone PostHog repo: {e}")))?;

        if !clone_output.status.success() {
            let err = String::from_utf8_lossy(&clone_output.stderr);
            let err_msg = format!("Failed to clone PostHog repo: {err}");
            self.log(service_id, "error", &err_msg, "system").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(AppError::Internal(err_msg));
        }

        // Sparse checkout only the dirs we need
        let sparse_output = tokio::process::Command::new("git")
            .args([
                "sparse-checkout",
                "set",
                "docker/clickhouse",
                "posthog/idl",
                "posthog/user_scripts",
            ])
            .current_dir(&posthog_repo_dir)
            .output()
            .await
            .map_err(|e| AppError::Internal(format!("failed to sparse-checkout: {e}")))?;

        if !sparse_output.status.success() {
            let err = String::from_utf8_lossy(&sparse_output.stderr);
            self.log(service_id, "warn", &format!("sparse-checkout warning: {err}"), "system")
                .await?;
        }

        self.log(service_id, "info", "Writing environment configuration...", "system")
            .await?;

        let env_content = format!(
            r#"# PostHog Configuration (auto-generated by Rift)
POSTHOG_SECRET={secret_key}
ENCRYPTION_SALT_KEYS={encryption_salt}
POSTGRES_PASSWORD={postgres_password}
POSTHOG_WEB_PORT={web_port}
SITE_URL={scheme}://{public_host}:{web_port}
"#,
            secret_key = secret_key,
            encryption_salt = encryption_salt,
            postgres_password = postgres_password,
            scheme = self.proxy_scheme,
            public_host = self.public_host,
            web_port = self.posthog_web_port,
        );

        tokio::fs::write(service_dir.join(".env"), &env_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write .env: {e}")))?;

        self.log(service_id, "info", "Writing Docker Compose manifest...", "system")
            .await?;

        let compose_content = generate_posthog_compose();
        tokio::fs::write(service_dir.join("docker-compose.yml"), &compose_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write docker-compose.yml: {e}")))?;

        // Create compose/start and compose/wait scripts (mimics PostHog deploy-hobby)
        self.write_posthog_scripts(&service_dir).await?;

        self.log(service_id, "info", "Pulling PostHog Docker images...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["pull"], service_id)
            .await
        {
            let err_msg = format!("Failed to pull images: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        self.log(service_id, "info", "Starting PostHog services...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["up", "-d"], service_id)
            .await
        {
            let err_msg = format!("Failed to start services: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        self.connect_engine_to_service_network(service_id).await;

        self.log(service_id, "info", "Waiting for PostHog to be ready (this may take several minutes on first run — migrations are running)...", "system")
            .await?;

        let healthy = self
            .wait_for_posthog_health(service_id, &service_dir)
            .await;

        if healthy {
            let connection_info = serde_json::json!({
                "app_url": format!("{}://{}:{}", self.proxy_scheme, self.public_host, self.posthog_web_port),
                "internal_app_url": format!("http://{}-posthog-web-1:8000", service_id),
            });

            db_services::update_connection_info(&self.pool, service_id, &connection_info).await?;
            db_services::update_status_started(&self.pool, service_id, "running").await?;

            self.log(service_id, "info", "PostHog is ready!", "system")
                .await?;
        } else {
            let err_msg = "Health check timed out — PostHog may still be starting. Check logs for details.";
            self.log(service_id, "warn", err_msg, "system").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(err_msg)).await?;
        }

        Ok(())
    }

    pub async fn stop_posthog(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Stopping PostHog services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["stop"], service_id)
            .await?;

        db_services::update_status_stopped(&self.pool, service_id, "stopped").await?;
        self.log(service_id, "info", "PostHog stopped.", "system")
            .await?;

        Ok(())
    }

    pub async fn start_posthog(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Starting PostHog services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["start"], service_id)
            .await?;

        self.connect_engine_to_service_network(service_id).await;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "PostHog started.", "system")
            .await?;

        Ok(())
    }

    pub async fn restart_posthog(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Restarting PostHog services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["restart"], service_id)
            .await?;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "PostHog restarted.", "system")
            .await?;

        Ok(())
    }

    pub async fn remove_posthog(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        db_services::update_status(&self.pool, service_id, "removing", None).await?;

        self.log(service_id, "info", "Removing PostHog services and volumes...", "docker")
            .await?;

        let _ = self
            .run_compose_command(&service_dir, &["down", "-v", "--remove-orphans"], service_id)
            .await;

        let _ = tokio::fs::remove_dir_all(&service_dir).await;

        self.log(service_id, "info", "PostHog removed.", "system")
            .await?;

        Ok(())
    }

    async fn wait_for_posthog_health(&self, service_id: Uuid, service_dir: &Path) -> bool {
        // PostHog first-run includes DB migrations + ClickHouse migrations which can
        // take 5-10 minutes, so we allow up to 180 attempts * 5s = 15 minutes.
        let required_healthy = ["posthog-db", "posthog-redis", "posthog-clickhouse", "posthog-kafka"];

        for attempt in 1..=180 {
            tokio::time::sleep(std::time::Duration::from_secs(5)).await;

            let output = tokio::process::Command::new("docker")
                .args(["compose", "ps", "--format", "json"])
                .current_dir(service_dir)
                .output()
                .await;

            let output = match output {
                Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).to_string(),
                _ => {
                    if attempt % 10 == 0 {
                        self.log(
                            service_id,
                            "info",
                            &format!("Waiting for services... (attempt {attempt}/180)"),
                            "system",
                        )
                        .await
                        .ok();
                    }
                    continue;
                }
            };

            let mut all_healthy = true;
            let mut found = std::collections::HashSet::new();
            let mut web_running = false;

            for line in output.lines() {
                if let Ok(v) = serde_json::from_str::<serde_json::Value>(line) {
                    let service = v["Service"].as_str().unwrap_or("");
                    let health = v["Health"].as_str().unwrap_or("");
                    let state = v["State"].as_str().unwrap_or("");

                    if required_healthy.contains(&service) {
                        found.insert(service.to_string());
                        if health != "healthy" {
                            all_healthy = false;
                        }
                    }
                    if service == "posthog-web" && state == "running" {
                        web_running = true;
                    }
                }
            }

            if all_healthy && found.len() == required_healthy.len() && web_running {
                self.log(
                    service_id,
                    "info",
                    &format!("All services healthy (attempt {attempt}/180)"),
                    "system",
                )
                .await
                .ok();
                return true;
            }

            if attempt % 10 == 0 {
                let pending: Vec<_> = required_healthy
                    .iter()
                    .filter(|s| !found.contains(**s))
                    .copied()
                    .collect();
                self.log(
                    service_id,
                    "info",
                    &format!(
                        "Waiting for services... (attempt {attempt}/180, pending: {})",
                        if pending.is_empty() { "checking health".to_string() } else { pending.join(", ") }
                    ),
                    "system",
                )
                .await
                .ok();
            }
        }

        false
    }

    // ── n8n ─────────────────────────────────────────────────────────────

    pub async fn deploy_n8n(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        tokio::fs::create_dir_all(&service_dir)
            .await
            .map_err(|e| AppError::Internal(format!("failed to create service dir: {e}")))?;

        db_services::update_status(&self.pool, service_id, "deploying", None).await?;

        self.log(service_id, "info", "Generating n8n configuration...", "system")
            .await?;

        let encryption_key = generate_random_string(32);
        let jwt_secret = generate_random_string(32);
        let n8n_port = self.n8n_port;

        self.log(service_id, "info", "Writing environment configuration...", "system")
            .await?;

        let env_content = format!(
            r#"# n8n Configuration (auto-generated by Rift)
N8N_PORT=5678
N8N_HOST=0.0.0.0
N8N_PROTOCOL=http
N8N_ENCRYPTION_KEY={encryption_key}
N8N_USER_MANAGEMENT_JWT_SECRET={jwt_secret}
WEBHOOK_URL={scheme}://{public_host}:{n8n_port}
GENERIC_TIMEZONE=UTC
N8N_EXTERNAL_PORT={n8n_port}
"#,
            scheme = self.proxy_scheme,
            public_host = self.public_host,
        );

        tokio::fs::write(service_dir.join(".env"), &env_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write .env: {e}")))?;

        self.log(service_id, "info", "Writing Docker Compose manifest...", "system")
            .await?;

        let compose_content = generate_n8n_compose();
        tokio::fs::write(service_dir.join("docker-compose.yml"), &compose_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write docker-compose.yml: {e}")))?;

        // Create data volume directory
        tokio::fs::create_dir_all(service_dir.join("volumes/n8n"))
            .await
            .map_err(|e| AppError::Internal(format!("failed to create n8n data dir: {e}")))?;

        // Pull images
        self.log(service_id, "info", "Pulling n8n Docker image...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["pull"], service_id)
            .await
        {
            let err_msg = format!("Failed to pull images: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        // Start services
        self.log(service_id, "info", "Starting n8n...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["up", "-d"], service_id)
            .await
        {
            let err_msg = format!("Failed to start services: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        self.connect_engine_to_service_network(service_id).await;

        // Health check
        self.log(service_id, "info", "Waiting for n8n to be ready...", "system")
            .await?;

        let healthy = self
            .wait_for_health(service_id, &service_dir, &["n8n"])
            .await;

        if healthy {
            let connection_info = serde_json::json!({
                "editor_url": format!("{}://{}:{}", self.proxy_scheme, self.public_host, self.n8n_port),
                "internal_editor_url": format!("http://{}-n8n-1:5678", service_id),
                "webhook_url": format!("{}://{}:{}/webhook", self.proxy_scheme, self.public_host, self.n8n_port),
                "encryption_key": encryption_key,
            });

            db_services::update_connection_info(&self.pool, service_id, &connection_info).await?;
            db_services::update_status_started(&self.pool, service_id, "running").await?;

            self.log(service_id, "info", "n8n is ready!", "system")
                .await?;
        } else {
            let err_msg = "Health check timed out — n8n may still be starting";
            self.log(service_id, "warn", err_msg, "system").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(err_msg)).await?;
        }

        Ok(())
    }

    pub async fn stop_n8n(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Stopping n8n...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["stop"], service_id)
            .await?;

        db_services::update_status_stopped(&self.pool, service_id, "stopped").await?;
        self.log(service_id, "info", "n8n stopped.", "system")
            .await?;

        Ok(())
    }

    pub async fn start_n8n(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Starting n8n...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["start"], service_id)
            .await?;

        self.connect_engine_to_service_network(service_id).await;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "n8n started.", "system")
            .await?;

        Ok(())
    }

    pub async fn restart_n8n(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Restarting n8n...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["restart"], service_id)
            .await?;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "n8n restarted.", "system")
            .await?;

        Ok(())
    }

    pub async fn remove_n8n(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        db_services::update_status(&self.pool, service_id, "removing", None).await?;

        self.log(service_id, "info", "Removing n8n and volumes...", "docker")
            .await?;

        let _ = self
            .run_compose_command(&service_dir, &["down", "-v", "--remove-orphans"], service_id)
            .await;

        let _ = tokio::fs::remove_dir_all(&service_dir).await;

        self.log(service_id, "info", "n8n removed.", "system")
            .await?;

        Ok(())
    }

    pub async fn deploy_affine(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        tokio::fs::create_dir_all(&service_dir)
            .await
            .map_err(|e| AppError::Internal(format!("failed to create service dir: {e}")))?;

        db_services::update_status(&self.pool, service_id, "deploying", None).await?;

        self.log(service_id, "info", "Generating AFFiNE configuration...", "system")
            .await?;

        let postgres_password = generate_random_string(32);
        let affine_port = self.affine_port;

        self.log(service_id, "info", "Writing environment configuration...", "system")
            .await?;

        let env_content = format!(
            r#"# AFFiNE Configuration (auto-generated by Rift)
AFFINE_POSTGRES_PASSWORD={postgres_password}
AFFINE_DATABASE_URL=postgresql://affine:{postgres_password}@affine-db:5432/affine
AFFINE_REDIS_HOST=affine-redis
AFFINE_REDIS_PORT=6379
AFFINE_INDEXER=false
AFFINE_EXTERNAL_PORT={affine_port}
"#
        );

        tokio::fs::write(service_dir.join(".env"), &env_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write .env: {e}")))?;

        self.log(service_id, "info", "Writing Docker Compose manifest...", "system")
            .await?;

        let compose_content = generate_affine_compose();
        tokio::fs::write(service_dir.join("docker-compose.yml"), &compose_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write docker-compose.yml: {e}")))?;

        // Create volume directories
        for dir in ["volumes/postgres", "volumes/redis", "volumes/config", "volumes/storage"] {
            tokio::fs::create_dir_all(service_dir.join(dir))
                .await
                .map_err(|e| AppError::Internal(format!("failed to create {dir}: {e}")))?;
        }

        // Pull images
        self.log(service_id, "info", "Pulling AFFiNE Docker images...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["pull"], service_id)
            .await
        {
            let err_msg = format!("Failed to pull images: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        // Run AFFiNE pre-deploy migrations (starts db + redis via depends_on)
        self.log(service_id, "info", "Running AFFiNE database migrations...", "system")
            .await?;

        if let Err(e) = self
            .run_compose_command(
                &service_dir,
                &["run", "--rm", "affine", "node", "./scripts/self-host-predeploy.js"],
                service_id,
            )
            .await
        {
            let err_msg = format!("AFFiNE migration failed: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        // Start services
        self.log(service_id, "info", "Starting AFFiNE...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["up", "-d"], service_id)
            .await
        {
            let err_msg = format!("Failed to start services: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        self.connect_engine_to_service_network(service_id).await;

        // Health check
        self.log(service_id, "info", "Waiting for AFFiNE to be ready...", "system")
            .await?;

        let healthy = self
            .wait_for_health(service_id, &service_dir, &["affine"])
            .await;

        if healthy {
            let connection_info = serde_json::json!({
                "app_url": format!("{}://{}:{}", self.proxy_scheme, self.public_host, self.affine_port),
                "internal_app_url": format!("http://{}-affine-1:3010", service_id),
            });

            db_services::update_connection_info(&self.pool, service_id, &connection_info).await?;
            db_services::update_status_started(&self.pool, service_id, "running").await?;

            self.log(service_id, "info", "AFFiNE is ready!", "system")
                .await?;
        } else {
            let err_msg = "Health check timed out — AFFiNE may still be starting";
            self.log(service_id, "warn", err_msg, "system").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(err_msg)).await?;
        }

        Ok(())
    }

    pub async fn stop_affine(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Stopping AFFiNE...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["stop"], service_id)
            .await?;

        db_services::update_status_stopped(&self.pool, service_id, "stopped").await?;
        self.log(service_id, "info", "AFFiNE stopped.", "system")
            .await?;

        Ok(())
    }

    pub async fn start_affine(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Starting AFFiNE...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["start"], service_id)
            .await?;

        self.connect_engine_to_service_network(service_id).await;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "AFFiNE started.", "system")
            .await?;

        Ok(())
    }

    pub async fn restart_affine(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Restarting AFFiNE...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["restart"], service_id)
            .await?;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "AFFiNE restarted.", "system")
            .await?;

        Ok(())
    }

    pub async fn remove_affine(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        db_services::update_status(&self.pool, service_id, "removing", None).await?;

        self.log(service_id, "info", "Removing AFFiNE and volumes...", "docker")
            .await?;

        let _ = self
            .run_compose_command(&service_dir, &["down", "-v", "--remove-orphans"], service_id)
            .await;

        let _ = tokio::fs::remove_dir_all(&service_dir).await;

        self.log(service_id, "info", "AFFiNE removed.", "system")
            .await?;

        Ok(())
    }

    /// Connect the engine container to the Supabase service's Docker network.
    /// This allows the proxy to forward requests to containers (kong, studio)
    /// by their internal hostnames. The Supabase DB is named 'supabase-db' to
    /// avoid DNS conflicts with the Rift 'db' on the engine's default network.
    /// Silently ignores errors (e.g., already connected, not in Docker).
    pub async fn connect_engine_to_service_network(&self, service_id: Uuid) {
        // Detect our container ID from /etc/hostname (Docker sets this).
        let hostname = match tokio::fs::read_to_string("/etc/hostname").await {
            Ok(h) => h.trim().to_string(),
            Err(_) => return, // Not in a container — localhost works fine in dev
        };
        if hostname.is_empty() {
            return;
        }

        let network = format!("{}_default", service_id);
        let result = tokio::process::Command::new("docker")
            .args(["network", "connect", &network, &hostname])
            .output()
            .await;

        match result {
            Ok(output) if output.status.success() => {
                self.log(
                    service_id,
                    "info",
                    &format!("Connected engine to service network {network}"),
                    "system",
                )
                .await
                .ok();
            }
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr);
                // "already exists" means we're already connected — not an error
                if !stderr.contains("already exists") {
                    self.log(
                        service_id,
                        "warn",
                        &format!("Could not connect to service network: {}", stderr.trim()),
                        "system",
                    )
                    .await
                    .ok();
                }
            }
            Err(_) => {} // Docker command not available
        }
    }

    async fn run_compose_command(
        &self,
        service_dir: &Path,
        args: &[&str],
        service_id: Uuid,
    ) -> Result<(), AppError> {
        let mut cmd = tokio::process::Command::new("docker");
        cmd.arg("compose")
            .args(args)
            .current_dir(service_dir)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());

        let display = format!("docker compose {}", args.join(" "));
        self.log(service_id, "info", &format!("$ {display}"), "docker")
            .await?;

        let mut child = cmd.spawn().map_err(|e| {
            AppError::Internal(format!("failed to spawn '{display}': {e}"))
        })?;

        let stdout = child.stdout.take();
        let stderr = child.stderr.take();

        let pool_clone = self.pool.clone();
        let broadcaster_clone = self.service_log_broadcaster.clone();
        let sid = service_id;

        let stdout_task = tokio::spawn(async move {
            if let Some(stream) = stdout {
                let mut lines = BufReader::new(stream).lines();
                while let Ok(Some(line)) = lines.next_line().await {
                    let _ = insert_and_broadcast_service_log(
                        &pool_clone,
                        &broadcaster_clone,
                        sid,
                        "info",
                        &line,
                        "docker",
                    )
                    .await;
                }
            }
        });

        let pool_clone2 = self.pool.clone();
        let broadcaster_clone2 = self.service_log_broadcaster.clone();

        let stderr_task = tokio::spawn(async move {
            if let Some(stream) = stderr {
                let mut lines = BufReader::new(stream).lines();
                while let Ok(Some(line)) = lines.next_line().await {
                    let _ = insert_and_broadcast_service_log(
                        &pool_clone2,
                        &broadcaster_clone2,
                        sid,
                        "error",
                        &line,
                        "docker",
                    )
                    .await;
                }
            }
        });

        let status = child.wait().await.map_err(|e| {
            AppError::Internal(format!("failed waiting for '{display}': {e}"))
        })?;

        let _ = stdout_task.await;
        let _ = stderr_task.await;

        if status.success() {
            Ok(())
        } else {
            Err(AppError::Internal(format!(
                "command failed with status {:?}: {display}",
                status.code()
            )))
        }
    }

    async fn wait_for_health(&self, service_id: Uuid, service_dir: &Path, required_healthy: &[&str]) -> bool {
        // Check health via `docker compose ps --format json` since the engine
        // container can't reach published ports on the host network.

        for attempt in 1..=90 {
            tokio::time::sleep(std::time::Duration::from_secs(5)).await;

            let output = tokio::process::Command::new("docker")
                .args(["compose", "ps", "--format", "json"])
                .current_dir(service_dir)
                .output()
                .await;

            let output = match output {
                Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).to_string(),
                _ => {
                    if attempt % 10 == 0 {
                        self.log(
                            service_id,
                            "info",
                            &format!("Waiting for services... (attempt {attempt}/90)"),
                            "system",
                        )
                        .await
                        .ok();
                    }
                    continue;
                }
            };

            // Parse each line as JSON, check Health field for required services
            let mut all_healthy = true;
            let mut found = std::collections::HashSet::new();
            for line in output.lines() {
                if let Ok(v) = serde_json::from_str::<serde_json::Value>(line) {
                    let service = v["Service"].as_str().unwrap_or("");
                    let health = v["Health"].as_str().unwrap_or("");
                    if required_healthy.contains(&service) {
                        found.insert(service.to_string());
                        if health != "healthy" {
                            all_healthy = false;
                        }
                    }
                }
            }

            if all_healthy && found.len() == required_healthy.len() {
                self.log(
                    service_id,
                    "info",
                    &format!("All services healthy (attempt {attempt}/90)"),
                    "system",
                )
                .await
                .ok();
                return true;
            }

            if attempt % 10 == 0 {
                let unhealthy: Vec<_> = required_healthy
                    .iter()
                    .filter(|s| !found.contains(**s))
                    .copied()
                    .collect();
                self.log(
                    service_id,
                    "info",
                    &format!(
                        "Waiting for services... (attempt {attempt}/90, pending: {})",
                        if unhealthy.is_empty() { "checking health".to_string() } else { unhealthy.join(", ") }
                    ),
                    "system",
                )
                .await
                .ok();
            }
        }

        false
    }

    async fn log(
        &self,
        service_id: Uuid,
        level: &str,
        message: &str,
        source: &str,
    ) -> Result<(), AppError> {
        insert_and_broadcast_service_log(
            &self.pool,
            &self.service_log_broadcaster,
            service_id,
            level,
            message,
            source,
        )
        .await
    }

    async fn write_posthog_scripts(&self, service_dir: &Path) -> Result<(), AppError> {
        let compose_dir = service_dir.join("compose");
        tokio::fs::create_dir_all(&compose_dir)
            .await
            .map_err(|e| AppError::Internal(format!("failed to create compose dir: {e}")))?;

        // compose/wait — Python script that waits for ClickHouse + Postgres
        let wait_script = r#"#!/usr/bin/env python3
import socket, sys, time

def wait_for(host, port, name, timeout=300):
    start = time.time()
    while time.time() - start < timeout:
        try:
            s = socket.create_connection((host, port), timeout=5)
            s.close()
            print(f"{name} is ready")
            return
        except (ConnectionRefusedError, OSError):
            time.sleep(2)
    print(f"Timeout waiting for {name}")
    sys.exit(1)

wait_for("posthog-clickhouse", 9000, "ClickHouse")
wait_for("posthog-db", 5432, "PostgreSQL")
wait_for("posthog-redis", 6379, "Redis")
wait_for("posthog-kafka", 9092, "Kafka")
"#;

        // compose/start — entrypoint that waits, migrates, then starts server
        // Uses PostHog's built-in ./bin/migrate and ./bin/docker-server-unit scripts.
        // The image supports Granian (ASGI) when USE_GRANIAN=true (set in compose env).
        let start_script = r#"#!/bin/bash
set -e
echo "Waiting for dependencies..."
python3 /compose/wait
echo "Running database migrations..."
./bin/migrate
echo "Starting PostHog web server..."
exec ./bin/docker-server-unit
"#;

        tokio::fs::write(compose_dir.join("wait"), wait_script)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write compose/wait: {e}")))?;
        tokio::fs::write(compose_dir.join("start"), start_script)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write compose/start: {e}")))?;

        // Make scripts executable
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = std::fs::Permissions::from_mode(0o755);
            std::fs::set_permissions(compose_dir.join("wait"), perms.clone()).ok();
            std::fs::set_permissions(compose_dir.join("start"), perms).ok();
        }

        Ok(())
    }

    async fn write_supabase_configs(
        &self,
        service_dir: &Path,
        anon_key: &str,
        service_role_key: &str,
        jwt_secret: &str,
    ) -> Result<(), AppError> {
        // Create volumes directories that Supabase expects
        let volumes_dir = service_dir.join("volumes");
        for dir in &[
            "api",
            "db/init",
            "db/data",
            "storage",
            "functions",
        ] {
            tokio::fs::create_dir_all(volumes_dir.join(dir))
                .await
                .map_err(|e| {
                    AppError::Internal(format!("failed to create volume dir {dir}: {e}"))
                })?;
        }

        // Write Kong config with pre-rendered keys
        let kong_yml = include_str!("templates/kong.yml")
            .replace("${SUPABASE_ANON_KEY}", anon_key)
            .replace("${SUPABASE_SERVICE_KEY}", service_role_key);
        tokio::fs::write(volumes_dir.join("api/kong.yml"), &kong_yml)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write kong.yml: {e}")))?;

        // Write DB init script: set JWT secret on database + set passwords for Supabase roles
        // Uses psql \set variable substitution (same approach as official Supabase setup)
        // This runs inside init-scripts/ which is processed by migrate.sh BEFORE the
        // demotion migration that removes superuser from postgres role.
        let init_sql = format!(
            r#"\set db_password `echo "$POSTGRES_PASSWORD"`

ALTER DATABASE postgres SET "app.settings.jwt_secret" TO '{jwt_secret}';
ALTER DATABASE postgres SET "app.settings.jwt_exp" TO '3600';

ALTER ROLE authenticator WITH PASSWORD :'db_password';
ALTER ROLE supabase_auth_admin WITH PASSWORD :'db_password';
ALTER ROLE supabase_storage_admin WITH PASSWORD :'db_password';
"#
        );
        tokio::fs::write(volumes_dir.join("db/init/99-roles.sql"), &init_sql)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write db init script: {e}")))?;

        Ok(())
    }
}

async fn insert_and_broadcast_service_log(
    pool: &sqlx::PgPool,
    broadcaster: &ServiceLogBroadcaster,
    service_id: Uuid,
    level: &str,
    message: &str,
    source: &str,
) -> Result<(), AppError> {
    let log = db_services::insert_log_returning(pool, service_id, level, message, source).await?;
    broadcaster
        .send(
            service_id,
            ServiceLogMessage {
                id: log.id,
                service_id: log.service_id,
                timestamp: log.timestamp,
                level: log.level,
                message: log.message,
                source: log.source,
            },
        )
        .await;
    Ok(())
}

fn generate_random_string(len: usize) -> String {
    let mut rng = rand::thread_rng();
    let chars: Vec<char> = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        .chars()
        .collect();
    (0..len).map(|_| chars[rng.gen_range(0..chars.len())]).collect()
}

fn generate_hex_string(len: usize) -> String {
    let mut rng = rand::thread_rng();
    let hex_chars: Vec<char> = "0123456789abcdef".chars().collect();
    (0..len).map(|_| hex_chars[rng.gen_range(0..hex_chars.len())]).collect()
}

fn generate_supabase_jwt(jwt_secret: &str, role: &str) -> String {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    let header = URL_SAFE_NO_PAD.encode(r#"{"alg":"HS256","typ":"JWT"}"#);

    // Expire in ~10 years
    let exp = chrono::Utc::now().timestamp() + 315_360_000;
    let payload_json = format!(
        r#"{{"role":"{role}","iss":"supabase","iat":{},"exp":{exp}}}"#,
        chrono::Utc::now().timestamp()
    );
    let payload = URL_SAFE_NO_PAD.encode(&payload_json);

    let unsigned = format!("{header}.{payload}");
    let mut mac =
        Hmac::<Sha256>::new_from_slice(jwt_secret.as_bytes()).expect("HMAC key length is valid");
    mac.update(unsigned.as_bytes());
    let signature = URL_SAFE_NO_PAD.encode(mac.finalize().into_bytes());

    format!("{unsigned}.{signature}")
}

fn generate_supabase_compose() -> String {
    r#"# Supabase Docker Compose (managed by Rift)
services:
  studio:
    image: supabase/studio:2026.03.02-sha-5644bee
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const os=require('os');fetch('http://'+os.hostname()+':3000/api/platform/profile').then(r=>{if(r.status<200||r.status>=400)throw Error()})"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      meta:
        condition: service_healthy
    environment:
      HOSTNAME: studio
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION}
      DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT}
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      AUTH_JWT_SECRET: ${JWT_SECRET}
      LOGFLARE_API_KEY: "fake-key"
      LOGFLARE_URL: http://localhost
      NEXT_PUBLIC_ENABLE_LOGS: "false"
      NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
      SNIPPETS_MANAGEMENT_FOLDER: /app/snippets
      EDGE_FUNCTIONS_MANAGEMENT_FOLDER: /app/edge-functions
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
    ports:
      - "${STUDIO_PORT}:3000"
    volumes:
      - ./volumes/snippets:/app/snippets:Z
      - ./volumes/functions:/app/edge-functions:Z

  kong:
    image: kong:2.8.1
    restart: unless-stopped
    entrypoint: bash -c 'cp ~/temp.yml ~/kong.yml && /docker-entrypoint.sh kong docker-start'
    ports:
      - "${KONG_HTTP_PORT}:8000/tcp"
    depends_on:
      supabase-db:
        condition: service_healthy
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
    volumes:
      - ./volumes/api/kong.yml:/home/kong/temp.yml:ro

  auth:
    image: supabase/gotrue:v2.187.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      supabase-db:
        condition: service_healthy
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP}
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}
      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM}
      GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: "false"

  rest:
    image: postgrest/postgrest:v14.0
    restart: unless-stopped
    depends_on:
      supabase-db:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: ${JWT_SECRET}
      PGRST_APP_SETTINGS_JWT_EXP: ${JWT_EXPIRY}
    command: "postgrest"

  realtime:
    image: supabase/realtime:v2.78.6
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sSfL", "--head", "-o", "/dev/null", "-H", "Authorization: Bearer ${SUPABASE_ANON_KEY}", "http://localhost:4000/api/tenants/realtime-dev/health"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      supabase-db:
        condition: service_healthy
    environment:
      PORT: "4000"
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: supabase_admin
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_AFTER_CONNECT_QUERY: "SET search_path TO realtime"
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: ${JWT_SECRET}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ERL_AFLAGS: "-proto_dist inet_tcp"
      DNS_NODES: "''"
      RLIMIT_NOFILE: "10000"
      APP_NAME: realtime
      SEED_SELF_HOST: "true"
      SU_PASSWORD: ${POSTGRES_PASSWORD}
      METRICS_JWT_SECRET: ${JWT_SECRET}

  storage:
    image: supabase/storage-api:v1.41.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/status"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      supabase-db:
        condition: service_healthy
      rest:
        condition: service_started
    environment:
      ANON_KEY: ${SUPABASE_ANON_KEY}
      SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      FILE_SIZE_LIMIT: "52428800"
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: stub
      GLOBAL_S3_BUCKET: stub
      IS_MULTITENANT: "false"
      STORAGE_S3_REGION: stub
    volumes:
      - ./volumes/storage:/var/lib/storage:z

  meta:
    image: supabase/postgres-meta:v0.96.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:8080/health').then(r=>{if(r.status!==200)throw Error()})"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      supabase-db:
        condition: service_healthy
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: ${POSTGRES_HOST}
      PG_META_DB_PORT: ${POSTGRES_PORT}
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}

  supabase-db:
    image: supabase/postgres:15.14.1.093
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres -h localhost
      timeout: 5s
      interval: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432/tcp"
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXPIRY}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data:Z
      - ./volumes/db/init/99-roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
"#
    .to_string()
}

fn generate_posthog_compose() -> String {
    r#"# PostHog Docker Compose (managed by Rift)
# Based on official PostHog hobby deployment
# Ref: https://github.com/PostHog/posthog/blob/master/docker-compose.hobby.yml
services:
  posthog-db:
    image: postgres:15.12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posthog"]
      interval: 5s
      timeout: 30s
      retries: 30
      start_period: 10s
    environment:
      POSTGRES_USER: posthog
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: posthog
    volumes:
      - postgres-data:/var/lib/postgresql/data

  posthog-redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
    volumes:
      - redis-data:/data

  # ZooKeeper is required by ClickHouse for distributed DDL coordination.
  # config.xml references <zookeeper><node><host>zookeeper</host></node></zookeeper>
  posthog-zookeeper:
    image: zookeeper:3.7.0
    restart: unless-stopped
    networks:
      default:
        aliases:
          - zookeeper
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
      - zookeeper-logs:/logs

  posthog-kafka:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.9
    restart: unless-stopped
    networks:
      default:
        aliases:
          - kafka
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://kafka:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://kafka:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr kafka:33145
      - --advertise-rpc-addr kafka:33145
      - --mode dev-container
      - --smp 1
      - --memory 1G
      - --reserve-memory 200M
      - --overprovisioned
      - --set redpanda.empty_seed_starts_cluster=false
      - --seeds kafka:33145
      - --set redpanda.auto_create_topics_enabled=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9644/v1/status/ready || exit 1"]
      interval: 3s
      timeout: 10s
      retries: 10
    depends_on:
      - posthog-zookeeper
    environment:
      KAFKA_LOG_RETENTION_MS: "3600000"
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"
      KAFKA_LOG_RETENTION_HOURS: "1"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  # ClickHouse config notes:
  # - config.xml references hosts "zookeeper" and "clickhouse" — network aliases handle this
  # - config.d/default.xml uses from_env="KAFKA_HOSTS" for named collections — set below
  # - ONLY default.xml is mounted into config.d/ (coordinator.xml/data_node.xml are for multi-node)
  # - SSL (https_port 8443) in config.xml will warn about missing certs but HTTP 8123 still works
  posthog-clickhouse:
    image: clickhouse/clickhouse-server:25.12.5.44
    restart: on-failure
    networks:
      default:
        aliases:
          - clickhouse
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"]
      interval: 3s
      timeout: 10s
      retries: 10
    depends_on:
      posthog-kafka:
        condition: service_healthy
      posthog-zookeeper:
        condition: service_started
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: "1"
      KAFKA_HOSTS: "kafka:9092"
    volumes:
      - ./posthog/posthog/idl:/idl:ro
      - ./posthog/docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./posthog/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./posthog/docker/clickhouse/config.d/default.xml:/etc/clickhouse-server/config.d/default.xml:ro
      - ./posthog/docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./posthog/docker/clickhouse/user_defined_function.xml:/etc/clickhouse-server/user_defined_function.xml:ro
      - ./posthog/posthog/user_scripts:/var/lib/clickhouse/user_scripts:ro
      - clickhouse-data:/var/lib/clickhouse

  posthog-objectstorage:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    entrypoint: sh
    command: -c 'mkdir -p /data/posthog && minio server --address ":19000" --console-address ":19001" /data'
    environment:
      MINIO_ROOT_USER: object_storage_root_user
      MINIO_ROOT_PASSWORD: object_storage_root_password
    volumes:
      - objectstorage:/data

  posthog-web:
    image: posthog/posthog:latest
    restart: unless-stopped
    command: /compose/start
    depends_on:
      posthog-db:
        condition: service_healthy
      posthog-redis:
        condition: service_healthy
      posthog-clickhouse:
        condition: service_healthy
      posthog-kafka:
        condition: service_healthy
      posthog-objectstorage:
        condition: service_started
    ports:
      - "${POSTHOG_WEB_PORT}:8000"
    environment:
      SECRET_KEY: ${POSTHOG_SECRET}
      ENCRYPTION_SALT_KEYS: ${ENCRYPTION_SALT_KEYS}
      DATABASE_URL: postgres://posthog:${POSTGRES_PASSWORD}@posthog-db:5432/posthog
      REDIS_URL: redis://posthog-redis:6379/
      CLICKHOUSE_HOST: posthog-clickhouse
      CLICKHOUSE_DATABASE: posthog
      CLICKHOUSE_SECURE: "false"
      CLICKHOUSE_VERIFY: "false"
      CLICKHOUSE_API_USER: api
      CLICKHOUSE_API_PASSWORD: apipass
      CLICKHOUSE_APP_USER: app
      CLICKHOUSE_APP_PASSWORD: apppass
      KAFKA_HOSTS: posthog-kafka:9092
      SITE_URL: ${SITE_URL}
      DISABLE_SECURE_SSL_REDIRECT: "true"
      IS_BEHIND_PROXY: "true"
      TRUST_ALL_PROXIES: "true"
      OBJECT_STORAGE_ENABLED: "true"
      OBJECT_STORAGE_ENDPOINT: http://posthog-objectstorage:19000
      OBJECT_STORAGE_ACCESS_KEY_ID: object_storage_root_user
      OBJECT_STORAGE_SECRET_ACCESS_KEY: object_storage_root_password
      PGHOST: posthog-db
      PGUSER: posthog
      PGPASSWORD: ${POSTGRES_PASSWORD}
      DEPLOYMENT: hobby
      OPT_OUT_CAPTURE: "true"
      OTEL_SDK_DISABLED: "true"
      USE_GRANIAN: "true"
      GRANIAN_WORKERS: "2"
      CDP_API_URL: http://posthog-plugins:6738
      FLAGS_REDIS_ENABLED: "false"
      SKIP_ASYNC_MIGRATIONS_SETUP: "0"
    volumes:
      - ./compose:/compose:ro

  posthog-worker:
    image: posthog/posthog:latest
    restart: unless-stopped
    command: ./bin/docker-worker-celery --with-scheduler
    depends_on:
      posthog-db:
        condition: service_healthy
      posthog-redis:
        condition: service_healthy
      posthog-clickhouse:
        condition: service_healthy
      posthog-kafka:
        condition: service_healthy
      posthog-web:
        condition: service_started
    environment:
      SECRET_KEY: ${POSTHOG_SECRET}
      ENCRYPTION_SALT_KEYS: ${ENCRYPTION_SALT_KEYS}
      DATABASE_URL: postgres://posthog:${POSTGRES_PASSWORD}@posthog-db:5432/posthog
      REDIS_URL: redis://posthog-redis:6379/
      CLICKHOUSE_HOST: posthog-clickhouse
      CLICKHOUSE_DATABASE: posthog
      CLICKHOUSE_SECURE: "false"
      CLICKHOUSE_VERIFY: "false"
      CLICKHOUSE_API_USER: api
      CLICKHOUSE_API_PASSWORD: apipass
      CLICKHOUSE_APP_USER: app
      CLICKHOUSE_APP_PASSWORD: apppass
      KAFKA_HOSTS: posthog-kafka:9092
      SITE_URL: ${SITE_URL}
      DISABLE_SECURE_SSL_REDIRECT: "true"
      IS_BEHIND_PROXY: "true"
      OBJECT_STORAGE_ENABLED: "true"
      OBJECT_STORAGE_ENDPOINT: http://posthog-objectstorage:19000
      OBJECT_STORAGE_ACCESS_KEY_ID: object_storage_root_user
      OBJECT_STORAGE_SECRET_ACCESS_KEY: object_storage_root_password
      PGHOST: posthog-db
      PGUSER: posthog
      PGPASSWORD: ${POSTGRES_PASSWORD}
      DEPLOYMENT: hobby
      POSTHOG_SKIP_MIGRATION_CHECKS: "1"
      OTEL_SDK_DISABLED: "true"
      CDP_API_URL: http://posthog-plugins:6738
      FLAGS_REDIS_ENABLED: "false"
      CDP_REDIS_HOST: posthog-redis
      CDP_REDIS_PORT: "6379"
      LOGS_REDIS_HOST: posthog-redis
      LOGS_REDIS_PORT: "6379"
      LOGS_REDIS_TLS: "false"
      SESSION_RECORDING_API_REDIS_HOST: posthog-redis
      SESSION_RECORDING_API_REDIS_PORT: "6379"

  posthog-plugins:
    image: ghcr.io/posthog/posthog-node:latest
    restart: unless-stopped
    command: node nodejs/dist/index.js
    depends_on:
      posthog-db:
        condition: service_healthy
      posthog-redis:
        condition: service_healthy
      posthog-clickhouse:
        condition: service_healthy
      posthog-kafka:
        condition: service_healthy
    environment:
      SECRET_KEY: ${POSTHOG_SECRET}
      ENCRYPTION_SALT_KEYS: ${ENCRYPTION_SALT_KEYS}
      DATABASE_URL: postgres://posthog:${POSTGRES_PASSWORD}@posthog-db:5432/posthog
      REDIS_URL: redis://posthog-redis:6379/
      CLICKHOUSE_HOST: posthog-clickhouse
      CLICKHOUSE_DATABASE: posthog
      CLICKHOUSE_SECURE: "false"
      CLICKHOUSE_VERIFY: "false"
      KAFKA_HOSTS: posthog-kafka:9092
      SITE_URL: ${SITE_URL}
      PGHOST: posthog-db
      PGUSER: posthog
      PGPASSWORD: ${POSTGRES_PASSWORD}
      DEPLOYMENT: hobby
      CDP_REDIS_HOST: posthog-redis
      CDP_REDIS_PORT: "6379"
      LOGS_REDIS_HOST: posthog-redis
      LOGS_REDIS_PORT: "6379"
      LOGS_REDIS_TLS: "false"
      SESSION_RECORDING_API_REDIS_HOST: posthog-redis
      SESSION_RECORDING_API_REDIS_PORT: "6379"

volumes:
  postgres-data:
  redis-data:
  zookeeper-data:
  zookeeper-datalog:
  zookeeper-logs:
  redpanda-data:
  clickhouse-data:
  objectstorage:
"#
    .to_string()
}

fn generate_n8n_compose() -> String {
    r#"# n8n Docker Compose (managed by Rift)
services:
  n8n:
    image: n8nio/n8n:1.76.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_USER_MANAGEMENT_JWT_SECRET: ${N8N_USER_MANAGEMENT_JWT_SECRET}
      WEBHOOK_URL: ${WEBHOOK_URL}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
    ports:
      - "${N8N_EXTERNAL_PORT}:5678"
    volumes:
      - ./volumes/n8n:/home/node/.n8n
"#
    .to_string()
}

fn generate_affine_compose() -> String {
    r#"# AFFiNE Docker Compose (managed by Rift)
services:
  affine:
    image: ghcr.io/toeverything/affine:stable
    restart: unless-stopped
    depends_on:
      affine-db:
        condition: service_healthy
      affine-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:3010/').then(r=>{process.exit(r.ok?0:1)}).catch(()=>process.exit(1))\""]
      timeout: 5s
      interval: 10s
      retries: 5
      start_period: 90s
    environment:
      AFFINE_SERVER_HOST: "0.0.0.0"
      AFFINE_SERVER_PORT: "3010"
      DATABASE_URL: ${AFFINE_DATABASE_URL}
      REDIS_SERVER_HOST: ${AFFINE_REDIS_HOST}
      REDIS_SERVER_PORT: ${AFFINE_REDIS_PORT}
      AFFINE_INDEXER_ENABLED: ${AFFINE_INDEXER}
    ports:
      - "${AFFINE_EXTERNAL_PORT}:3010"
    volumes:
      - ./volumes/config:/root/.affine/config
      - ./volumes/storage:/root/.affine/storage

  affine-db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U affine -d affine"]
      timeout: 5s
      interval: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: ${AFFINE_POSTGRES_PASSWORD}
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  affine-redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - ./volumes/redis:/data
"#
    .to_string()
}
