use std::path::{Path, PathBuf};
use std::process::Stdio;

use rand::Rng;
use tokio::io::{AsyncBufReadExt, BufReader};
use uuid::Uuid;

use crate::{
    db::services as db_services,
    error::AppError,
    ws::{service_broadcast::ServiceLogMessage, ServiceLogBroadcaster},
};

#[derive(Clone)]
pub struct DockerComposeManager {
    pool: sqlx::PgPool,
    service_log_broadcaster: ServiceLogBroadcaster,
    data_dir: PathBuf,
    kong_port: u16,
    studio_port: u16,
    db_port: u16,
}

impl DockerComposeManager {
    pub fn new(
        pool: sqlx::PgPool,
        service_log_broadcaster: ServiceLogBroadcaster,
        data_dir: PathBuf,
        kong_port: u16,
        studio_port: u16,
        db_port: u16,
    ) -> Self {
        Self {
            pool,
            service_log_broadcaster,
            data_dir,
            kong_port,
            studio_port,
            db_port,
        }
    }

    pub async fn deploy_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        tokio::fs::create_dir_all(&service_dir)
            .await
            .map_err(|e| AppError::Internal(format!("failed to create service dir: {e}")))?;

        // Update status to deploying
        db_services::update_status(&self.pool, service_id, "deploying", None).await?;

        self.log(service_id, "info", "Generating Supabase configuration...", "system")
            .await?;

        // Generate secrets
        let jwt_secret = generate_random_string(64);
        let postgres_password = generate_random_string(32);
        let dashboard_password = generate_random_string(24);
        let secret_key_base = generate_hex_string(64);
        let anon_key = generate_supabase_jwt(&jwt_secret, "anon");
        let service_role_key = generate_supabase_jwt(&jwt_secret, "service_role");

        self.log(service_id, "info", "Writing environment configuration...", "system")
            .await?;

        // Write .env
        let env_content = format!(
            r#"# Supabase Configuration (auto-generated by Rift)
POSTGRES_PASSWORD={postgres_password}
JWT_SECRET={jwt_secret}
SUPABASE_ANON_KEY={anon_key}
SUPABASE_SERVICE_KEY={service_role_key}
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD={dashboard_password}
SECRET_KEY_BASE={secret_key_base}

POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

KONG_HTTP_PORT={kong_port}
STUDIO_PORT={studio_port}
POSTGRES_EXTERNAL_PORT={db_port}

API_EXTERNAL_URL=http://localhost:{kong_port}
SUPABASE_PUBLIC_URL=http://localhost:{kong_port}

SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false

STUDIO_DEFAULT_ORGANIZATION=Rift
STUDIO_DEFAULT_PROJECT=Default
"#,
            postgres_password = postgres_password,
            jwt_secret = jwt_secret,
            anon_key = anon_key,
            service_role_key = service_role_key,
            dashboard_password = dashboard_password,
            secret_key_base = secret_key_base,
            kong_port = self.kong_port,
            studio_port = self.studio_port,
            db_port = self.db_port,
        );

        tokio::fs::write(service_dir.join(".env"), &env_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write .env: {e}")))?;

        self.log(service_id, "info", "Writing Docker Compose manifest...", "system")
            .await?;

        // Write docker-compose.yml
        let compose_content = generate_supabase_compose();
        tokio::fs::write(service_dir.join("docker-compose.yml"), &compose_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write docker-compose.yml: {e}")))?;

        // Write required config files
        self.write_supabase_configs(&service_dir, &anon_key, &service_role_key, &jwt_secret).await?;

        // Remove old DB data so init scripts re-run on fresh deploy
        let db_data_dir = service_dir.join("volumes/db/data");
        if db_data_dir.exists() {
            tokio::fs::remove_dir_all(&db_data_dir).await.ok();
            tokio::fs::create_dir_all(&db_data_dir).await.map_err(|e| {
                AppError::Internal(format!("failed to recreate db data dir: {e}"))
            })?;
        }

        // Pull images
        self.log(service_id, "info", "Pulling Supabase Docker images...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["pull"], service_id)
            .await
        {
            let err_msg = format!("Failed to pull images: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        // Start services
        self.log(service_id, "info", "Starting Supabase services...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["up", "-d"], service_id)
            .await
        {
            let err_msg = format!("Failed to start services: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        // Connect engine container to the service's Docker network so the proxy
        // can reach Supabase containers (kong, studio, etc.) by container name.
        self.connect_engine_to_service_network(service_id).await;

        // Health check
        self.log(service_id, "info", "Waiting for Supabase to be ready...", "system")
            .await?;

        let healthy = self
            .wait_for_health(service_id, &service_dir)
            .await;

        if healthy {
            // Store connection info.
            // `internal_*_url` use Docker container names reachable from the engine
            // container (after network connect). The proxy uses these for forwarding.
            // `api_url` / `studio_url` use localhost ports for direct user access.
            let connection_info = serde_json::json!({
                "api_url": format!("http://localhost:{}", self.kong_port),
                "studio_url": format!("http://localhost:{}", self.studio_port),
                "internal_api_url": format!("http://{}-kong-1:8000", service_id),
                "internal_studio_url": format!("http://{}-studio-1:3000", service_id),
                "db_connection_string": format!(
                    "postgresql://postgres:{}@localhost:{}/postgres",
                    postgres_password, self.db_port
                ),
                "anon_key": anon_key,
                "service_role_key": service_role_key,
            });

            db_services::update_connection_info(&self.pool, service_id, &connection_info).await?;
            db_services::update_status_started(&self.pool, service_id, "running").await?;

            self.log(service_id, "info", "Supabase is ready!", "system")
                .await?;
        } else {
            let err_msg = "Health check timed out — Supabase may still be starting";
            self.log(service_id, "warn", err_msg, "system").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(err_msg)).await?;
        }

        Ok(())
    }

    pub async fn stop_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Stopping Supabase services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["stop"], service_id)
            .await?;

        db_services::update_status_stopped(&self.pool, service_id, "stopped").await?;
        self.log(service_id, "info", "Supabase stopped.", "system")
            .await?;

        Ok(())
    }

    pub async fn start_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Starting Supabase services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["start"], service_id)
            .await?;

        // Re-ensure engine is connected to the service network (may have been
        // lost if the engine container was restarted).
        self.connect_engine_to_service_network(service_id).await;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "Supabase started.", "system")
            .await?;

        Ok(())
    }

    pub async fn restart_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Restarting Supabase services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["restart"], service_id)
            .await?;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "Supabase restarted.", "system")
            .await?;

        Ok(())
    }

    pub async fn remove_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        db_services::update_status(&self.pool, service_id, "removing", None).await?;

        self.log(service_id, "info", "Removing Supabase services and volumes...", "docker")
            .await?;

        // Ignore errors during removal — service dir may not exist
        let _ = self
            .run_compose_command(&service_dir, &["down", "-v", "--remove-orphans"], service_id)
            .await;

        // Clean up the service directory
        let _ = tokio::fs::remove_dir_all(&service_dir).await;

        self.log(service_id, "info", "Supabase removed.", "system")
            .await?;

        Ok(())
    }

    /// Connect the engine container to the Supabase service's Docker network.
    /// This allows the proxy to forward requests to containers (kong, studio)
    /// by their internal hostnames. Silently ignores errors (e.g., already
    /// connected, not running inside Docker).
    async fn connect_engine_to_service_network(&self, service_id: Uuid) {
        // Detect our container ID from /etc/hostname (Docker sets this).
        let hostname = match tokio::fs::read_to_string("/etc/hostname").await {
            Ok(h) => h.trim().to_string(),
            Err(_) => return, // Not in a container — localhost works fine in dev
        };
        if hostname.is_empty() {
            return;
        }

        let network = format!("{}_default", service_id);
        let result = tokio::process::Command::new("docker")
            .args(["network", "connect", &network, &hostname])
            .output()
            .await;

        match result {
            Ok(output) if output.status.success() => {
                self.log(
                    service_id,
                    "info",
                    &format!("Connected engine to service network {network}"),
                    "system",
                )
                .await
                .ok();
            }
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr);
                // "already exists" means we're already connected — not an error
                if !stderr.contains("already exists") {
                    self.log(
                        service_id,
                        "warn",
                        &format!("Could not connect to service network: {}", stderr.trim()),
                        "system",
                    )
                    .await
                    .ok();
                }
            }
            Err(_) => {} // Docker command not available
        }
    }

    async fn run_compose_command(
        &self,
        service_dir: &Path,
        args: &[&str],
        service_id: Uuid,
    ) -> Result<(), AppError> {
        let mut cmd = tokio::process::Command::new("docker");
        cmd.arg("compose")
            .args(args)
            .current_dir(service_dir)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());

        let display = format!("docker compose {}", args.join(" "));
        self.log(service_id, "info", &format!("$ {display}"), "docker")
            .await?;

        let mut child = cmd.spawn().map_err(|e| {
            AppError::Internal(format!("failed to spawn '{display}': {e}"))
        })?;

        let stdout = child.stdout.take();
        let stderr = child.stderr.take();

        let pool_clone = self.pool.clone();
        let broadcaster_clone = self.service_log_broadcaster.clone();
        let sid = service_id;

        let stdout_task = tokio::spawn(async move {
            if let Some(stream) = stdout {
                let mut lines = BufReader::new(stream).lines();
                while let Ok(Some(line)) = lines.next_line().await {
                    let _ = insert_and_broadcast_service_log(
                        &pool_clone,
                        &broadcaster_clone,
                        sid,
                        "info",
                        &line,
                        "docker",
                    )
                    .await;
                }
            }
        });

        let pool_clone2 = self.pool.clone();
        let broadcaster_clone2 = self.service_log_broadcaster.clone();

        let stderr_task = tokio::spawn(async move {
            if let Some(stream) = stderr {
                let mut lines = BufReader::new(stream).lines();
                while let Ok(Some(line)) = lines.next_line().await {
                    let _ = insert_and_broadcast_service_log(
                        &pool_clone2,
                        &broadcaster_clone2,
                        sid,
                        "error",
                        &line,
                        "docker",
                    )
                    .await;
                }
            }
        });

        let status = child.wait().await.map_err(|e| {
            AppError::Internal(format!("failed waiting for '{display}': {e}"))
        })?;

        let _ = stdout_task.await;
        let _ = stderr_task.await;

        if status.success() {
            Ok(())
        } else {
            Err(AppError::Internal(format!(
                "command failed with status {:?}: {display}",
                status.code()
            )))
        }
    }

    async fn wait_for_health(&self, service_id: Uuid, service_dir: &Path) -> bool {
        // Check health via `docker compose ps --format json` since the engine
        // container can't reach Kong's published port on the host network.
        let required_healthy = ["db", "kong", "auth", "realtime", "storage", "meta"];

        for attempt in 1..=90 {
            tokio::time::sleep(std::time::Duration::from_secs(5)).await;

            let output = tokio::process::Command::new("docker")
                .args(["compose", "ps", "--format", "json"])
                .current_dir(service_dir)
                .output()
                .await;

            let output = match output {
                Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).to_string(),
                _ => {
                    if attempt % 10 == 0 {
                        self.log(
                            service_id,
                            "info",
                            &format!("Waiting for services... (attempt {attempt}/90)"),
                            "system",
                        )
                        .await
                        .ok();
                    }
                    continue;
                }
            };

            // Parse each line as JSON, check Health field for required services
            let mut all_healthy = true;
            let mut found = std::collections::HashSet::new();
            for line in output.lines() {
                if let Ok(v) = serde_json::from_str::<serde_json::Value>(line) {
                    let service = v["Service"].as_str().unwrap_or("");
                    let health = v["Health"].as_str().unwrap_or("");
                    if required_healthy.contains(&service) {
                        found.insert(service.to_string());
                        if health != "healthy" {
                            all_healthy = false;
                        }
                    }
                }
            }

            if all_healthy && found.len() == required_healthy.len() {
                self.log(
                    service_id,
                    "info",
                    &format!("All services healthy (attempt {attempt}/90)"),
                    "system",
                )
                .await
                .ok();
                return true;
            }

            if attempt % 10 == 0 {
                let unhealthy: Vec<_> = required_healthy
                    .iter()
                    .filter(|s| !found.contains(**s))
                    .copied()
                    .collect();
                self.log(
                    service_id,
                    "info",
                    &format!(
                        "Waiting for services... (attempt {attempt}/90, pending: {})",
                        if unhealthy.is_empty() { "checking health".to_string() } else { unhealthy.join(", ") }
                    ),
                    "system",
                )
                .await
                .ok();
            }
        }

        false
    }

    async fn log(
        &self,
        service_id: Uuid,
        level: &str,
        message: &str,
        source: &str,
    ) -> Result<(), AppError> {
        insert_and_broadcast_service_log(
            &self.pool,
            &self.service_log_broadcaster,
            service_id,
            level,
            message,
            source,
        )
        .await
    }

    async fn write_supabase_configs(
        &self,
        service_dir: &Path,
        anon_key: &str,
        service_role_key: &str,
        jwt_secret: &str,
    ) -> Result<(), AppError> {
        // Create volumes directories that Supabase expects
        let volumes_dir = service_dir.join("volumes");
        for dir in &[
            "api",
            "db/init",
            "db/data",
            "storage",
            "functions",
        ] {
            tokio::fs::create_dir_all(volumes_dir.join(dir))
                .await
                .map_err(|e| {
                    AppError::Internal(format!("failed to create volume dir {dir}: {e}"))
                })?;
        }

        // Write Kong config with pre-rendered keys
        let kong_yml = include_str!("templates/kong.yml")
            .replace("${SUPABASE_ANON_KEY}", anon_key)
            .replace("${SUPABASE_SERVICE_KEY}", service_role_key);
        tokio::fs::write(volumes_dir.join("api/kong.yml"), &kong_yml)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write kong.yml: {e}")))?;

        // Write DB init script: set JWT secret on database + set passwords for Supabase roles
        // Uses psql \set variable substitution (same approach as official Supabase setup)
        // This runs inside init-scripts/ which is processed by migrate.sh BEFORE the
        // demotion migration that removes superuser from postgres role.
        let init_sql = format!(
            r#"\set db_password `echo "$POSTGRES_PASSWORD"`

ALTER DATABASE postgres SET "app.settings.jwt_secret" TO '{jwt_secret}';
ALTER DATABASE postgres SET "app.settings.jwt_exp" TO '3600';

ALTER ROLE authenticator WITH PASSWORD :'db_password';
ALTER ROLE supabase_auth_admin WITH PASSWORD :'db_password';
ALTER ROLE supabase_storage_admin WITH PASSWORD :'db_password';
"#
        );
        tokio::fs::write(volumes_dir.join("db/init/99-roles.sql"), &init_sql)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write db init script: {e}")))?;

        Ok(())
    }
}

async fn insert_and_broadcast_service_log(
    pool: &sqlx::PgPool,
    broadcaster: &ServiceLogBroadcaster,
    service_id: Uuid,
    level: &str,
    message: &str,
    source: &str,
) -> Result<(), AppError> {
    let log = db_services::insert_log_returning(pool, service_id, level, message, source).await?;
    broadcaster
        .send(
            service_id,
            ServiceLogMessage {
                id: log.id,
                service_id: log.service_id,
                timestamp: log.timestamp,
                level: log.level,
                message: log.message,
                source: log.source,
            },
        )
        .await;
    Ok(())
}

fn generate_random_string(len: usize) -> String {
    let mut rng = rand::thread_rng();
    let chars: Vec<char> = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        .chars()
        .collect();
    (0..len).map(|_| chars[rng.gen_range(0..chars.len())]).collect()
}

fn generate_hex_string(len: usize) -> String {
    let mut rng = rand::thread_rng();
    let hex_chars: Vec<char> = "0123456789abcdef".chars().collect();
    (0..len).map(|_| hex_chars[rng.gen_range(0..hex_chars.len())]).collect()
}

fn generate_supabase_jwt(jwt_secret: &str, role: &str) -> String {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    let header = URL_SAFE_NO_PAD.encode(r#"{"alg":"HS256","typ":"JWT"}"#);

    // Expire in ~10 years
    let exp = chrono::Utc::now().timestamp() + 315_360_000;
    let payload_json = format!(
        r#"{{"role":"{role}","iss":"supabase","iat":{},"exp":{exp}}}"#,
        chrono::Utc::now().timestamp()
    );
    let payload = URL_SAFE_NO_PAD.encode(&payload_json);

    let unsigned = format!("{header}.{payload}");
    let mut mac =
        Hmac::<Sha256>::new_from_slice(jwt_secret.as_bytes()).expect("HMAC key length is valid");
    mac.update(unsigned.as_bytes());
    let signature = URL_SAFE_NO_PAD.encode(mac.finalize().into_bytes());

    format!("{unsigned}.{signature}")
}

fn generate_supabase_compose() -> String {
    r#"# Supabase Docker Compose (managed by Rift)
services:
  studio:
    image: supabase/studio:2026.03.02-sha-5644bee
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const os=require('os');fetch('http://'+os.hostname()+':3000/api/platform/profile').then(r=>{if(r.status<200||r.status>=400)throw Error()})"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      meta:
        condition: service_healthy
    environment:
      HOSTNAME: studio
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION}
      DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT}
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      AUTH_JWT_SECRET: ${JWT_SECRET}
      LOGFLARE_API_KEY: "fake-key"
      LOGFLARE_URL: http://localhost
      NEXT_PUBLIC_ENABLE_LOGS: "false"
      NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
    ports:
      - "${STUDIO_PORT}:3000"

  kong:
    image: kong:2.8.1
    restart: unless-stopped
    entrypoint: bash -c 'cp ~/temp.yml ~/kong.yml && /docker-entrypoint.sh kong docker-start'
    ports:
      - "${KONG_HTTP_PORT}:8000/tcp"
    depends_on:
      db:
        condition: service_healthy
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
    volumes:
      - ./volumes/api/kong.yml:/home/kong/temp.yml:ro

  auth:
    image: supabase/gotrue:v2.187.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP}
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}
      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM}
      GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: "false"

  rest:
    image: postgrest/postgrest:v14.0
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: ${JWT_SECRET}
      PGRST_APP_SETTINGS_JWT_EXP: ${JWT_EXPIRY}
    command: "postgrest"

  realtime:
    image: supabase/realtime:v2.78.6
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sSfL", "--head", "-o", "/dev/null", "-H", "Authorization: Bearer ${SUPABASE_ANON_KEY}", "http://localhost:4000/api/tenants/realtime-dev/health"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: "4000"
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: supabase_admin
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_AFTER_CONNECT_QUERY: "SET search_path TO realtime"
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: ${JWT_SECRET}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ERL_AFLAGS: "-proto_dist inet_tcp"
      DNS_NODES: "''"
      RLIMIT_NOFILE: "10000"
      APP_NAME: realtime
      SEED_SELF_HOST: "true"
      SU_PASSWORD: ${POSTGRES_PASSWORD}
      METRICS_JWT_SECRET: ${JWT_SECRET}

  storage:
    image: supabase/storage-api:v1.41.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/status"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      rest:
        condition: service_started
    environment:
      ANON_KEY: ${SUPABASE_ANON_KEY}
      SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      FILE_SIZE_LIMIT: "52428800"
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: stub
      GLOBAL_S3_BUCKET: stub
      IS_MULTITENANT: "false"
      STORAGE_S3_REGION: stub
    volumes:
      - ./volumes/storage:/var/lib/storage:z

  meta:
    image: supabase/postgres-meta:v0.96.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:8080/health').then(r=>{if(r.status!==200)throw Error()})"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: ${POSTGRES_HOST}
      PG_META_DB_PORT: ${POSTGRES_PORT}
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}

  db:
    image: supabase/postgres:15.14.1.093
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres -h localhost
      timeout: 5s
      interval: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432/tcp"
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXPIRY}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data:Z
      - ./volumes/db/init/99-roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
"#
    .to_string()
}
