use std::path::{Path, PathBuf};
use std::process::Stdio;

use rand::Rng;
use tokio::io::{AsyncBufReadExt, BufReader};
use uuid::Uuid;

use crate::{
    db::services as db_services,
    error::AppError,
    ws::{service_broadcast::ServiceLogMessage, ServiceLogBroadcaster},
};

#[derive(Clone)]
pub struct DockerComposeManager {
    pool: sqlx::PgPool,
    service_log_broadcaster: ServiceLogBroadcaster,
    data_dir: PathBuf,
    kong_port: u16,
    studio_port: u16,
    db_port: u16,
}

impl DockerComposeManager {
    pub fn new(
        pool: sqlx::PgPool,
        service_log_broadcaster: ServiceLogBroadcaster,
        data_dir: PathBuf,
        kong_port: u16,
        studio_port: u16,
        db_port: u16,
    ) -> Self {
        Self {
            pool,
            service_log_broadcaster,
            data_dir,
            kong_port,
            studio_port,
            db_port,
        }
    }

    pub async fn deploy_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        tokio::fs::create_dir_all(&service_dir)
            .await
            .map_err(|e| AppError::Internal(format!("failed to create service dir: {e}")))?;

        // Update status to deploying
        db_services::update_status(&self.pool, service_id, "deploying", None).await?;

        self.log(service_id, "info", "Generating Supabase configuration...", "system")
            .await?;

        // Generate secrets
        let jwt_secret = generate_random_string(64);
        let postgres_password = generate_random_string(32);
        let dashboard_password = generate_random_string(24);
        let anon_key = generate_supabase_jwt(&jwt_secret, "anon");
        let service_role_key = generate_supabase_jwt(&jwt_secret, "service_role");

        self.log(service_id, "info", "Writing environment configuration...", "system")
            .await?;

        // Write .env
        let env_content = format!(
            r#"# Supabase Configuration (auto-generated by Rift)
POSTGRES_PASSWORD={postgres_password}
JWT_SECRET={jwt_secret}
ANON_KEY={anon_key}
SERVICE_ROLE_KEY={service_role_key}
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD={dashboard_password}

POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

KONG_HTTP_PORT={kong_port}
STUDIO_PORT={studio_port}
POSTGRES_EXTERNAL_PORT={db_port}

API_EXTERNAL_URL=http://localhost:{kong_port}
SUPABASE_PUBLIC_URL=http://localhost:{kong_port}

SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false

STUDIO_DEFAULT_ORGANIZATION=Rift
STUDIO_DEFAULT_PROJECT=Default
"#,
            postgres_password = postgres_password,
            jwt_secret = jwt_secret,
            anon_key = anon_key,
            service_role_key = service_role_key,
            dashboard_password = dashboard_password,
            kong_port = self.kong_port,
            studio_port = self.studio_port,
            db_port = self.db_port,
        );

        tokio::fs::write(service_dir.join(".env"), &env_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write .env: {e}")))?;

        self.log(service_id, "info", "Writing Docker Compose manifest...", "system")
            .await?;

        // Write docker-compose.yml
        let compose_content = generate_supabase_compose();
        tokio::fs::write(service_dir.join("docker-compose.yml"), &compose_content)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write docker-compose.yml: {e}")))?;

        // Write required config files
        self.write_supabase_configs(&service_dir).await?;

        // Pull images
        self.log(service_id, "info", "Pulling Supabase Docker images...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["pull"], service_id)
            .await
        {
            let err_msg = format!("Failed to pull images: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        // Start services
        self.log(service_id, "info", "Starting Supabase services...", "docker")
            .await?;

        if let Err(e) = self
            .run_compose_command(&service_dir, &["up", "-d"], service_id)
            .await
        {
            let err_msg = format!("Failed to start services: {e}");
            self.log(service_id, "error", &err_msg, "docker").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(&err_msg)).await?;
            return Err(e);
        }

        // Health check
        self.log(service_id, "info", "Waiting for Supabase to be ready...", "system")
            .await?;

        let healthy = self
            .wait_for_health(service_id, &format!("http://localhost:{}", self.kong_port))
            .await;

        if healthy {
            // Store connection info
            let connection_info = serde_json::json!({
                "api_url": format!("http://localhost:{}", self.kong_port),
                "studio_url": format!("http://localhost:{}", self.studio_port),
                "db_connection_string": format!(
                    "postgresql://postgres:{}@localhost:{}/postgres",
                    postgres_password, self.db_port
                ),
                "anon_key": anon_key,
                "service_role_key": service_role_key,
            });

            db_services::update_connection_info(&self.pool, service_id, &connection_info).await?;
            db_services::update_status_started(&self.pool, service_id, "running").await?;

            self.log(service_id, "info", "Supabase is ready!", "system")
                .await?;
        } else {
            let err_msg = "Health check timed out — Supabase may still be starting";
            self.log(service_id, "warn", err_msg, "system").await?;
            db_services::update_status(&self.pool, service_id, "failed", Some(err_msg)).await?;
        }

        Ok(())
    }

    pub async fn stop_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Stopping Supabase services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["stop"], service_id)
            .await?;

        db_services::update_status_stopped(&self.pool, service_id, "stopped").await?;
        self.log(service_id, "info", "Supabase stopped.", "system")
            .await?;

        Ok(())
    }

    pub async fn start_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Starting Supabase services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["start"], service_id)
            .await?;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "Supabase started.", "system")
            .await?;

        Ok(())
    }

    pub async fn restart_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        self.log(service_id, "info", "Restarting Supabase services...", "docker")
            .await?;

        self.run_compose_command(&service_dir, &["restart"], service_id)
            .await?;

        db_services::update_status_started(&self.pool, service_id, "running").await?;
        self.log(service_id, "info", "Supabase restarted.", "system")
            .await?;

        Ok(())
    }

    pub async fn remove_supabase(&self, service_id: Uuid) -> Result<(), AppError> {
        let service_dir = self.data_dir.join(service_id.to_string());
        db_services::update_status(&self.pool, service_id, "removing", None).await?;

        self.log(service_id, "info", "Removing Supabase services and volumes...", "docker")
            .await?;

        // Ignore errors during removal — service dir may not exist
        let _ = self
            .run_compose_command(&service_dir, &["down", "-v", "--remove-orphans"], service_id)
            .await;

        // Clean up the service directory
        let _ = tokio::fs::remove_dir_all(&service_dir).await;

        self.log(service_id, "info", "Supabase removed.", "system")
            .await?;

        Ok(())
    }

    async fn run_compose_command(
        &self,
        service_dir: &Path,
        args: &[&str],
        service_id: Uuid,
    ) -> Result<(), AppError> {
        let mut cmd = tokio::process::Command::new("docker");
        cmd.arg("compose")
            .args(args)
            .current_dir(service_dir)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());

        let display = format!("docker compose {}", args.join(" "));
        self.log(service_id, "info", &format!("$ {display}"), "docker")
            .await?;

        let mut child = cmd.spawn().map_err(|e| {
            AppError::Internal(format!("failed to spawn '{display}': {e}"))
        })?;

        let stdout = child.stdout.take();
        let stderr = child.stderr.take();

        let pool_clone = self.pool.clone();
        let broadcaster_clone = self.service_log_broadcaster.clone();
        let sid = service_id;

        let stdout_task = tokio::spawn(async move {
            if let Some(stream) = stdout {
                let mut lines = BufReader::new(stream).lines();
                while let Ok(Some(line)) = lines.next_line().await {
                    let _ = insert_and_broadcast_service_log(
                        &pool_clone,
                        &broadcaster_clone,
                        sid,
                        "info",
                        &line,
                        "docker",
                    )
                    .await;
                }
            }
        });

        let pool_clone2 = self.pool.clone();
        let broadcaster_clone2 = self.service_log_broadcaster.clone();

        let stderr_task = tokio::spawn(async move {
            if let Some(stream) = stderr {
                let mut lines = BufReader::new(stream).lines();
                while let Ok(Some(line)) = lines.next_line().await {
                    let _ = insert_and_broadcast_service_log(
                        &pool_clone2,
                        &broadcaster_clone2,
                        sid,
                        "error",
                        &line,
                        "docker",
                    )
                    .await;
                }
            }
        });

        let status = child.wait().await.map_err(|e| {
            AppError::Internal(format!("failed waiting for '{display}': {e}"))
        })?;

        let _ = stdout_task.await;
        let _ = stderr_task.await;

        if status.success() {
            Ok(())
        } else {
            Err(AppError::Internal(format!(
                "command failed with status {:?}: {display}",
                status.code()
            )))
        }
    }

    async fn wait_for_health(&self, service_id: Uuid, api_url: &str) -> bool {
        let client = reqwest::Client::new();
        let health_url = format!("{api_url}/rest/v1/");

        for attempt in 1..=60 {
            tokio::time::sleep(std::time::Duration::from_secs(3)).await;

            match client.get(&health_url).send().await {
                Ok(resp) if resp.status().is_success() || resp.status().as_u16() == 401 => {
                    // 401 is expected (no auth header) but means the API is responding
                    self.log(
                        service_id,
                        "info",
                        &format!("Health check passed (attempt {attempt}/60)"),
                        "system",
                    )
                    .await
                    .ok();
                    return true;
                }
                Ok(resp) => {
                    if attempt % 10 == 0 {
                        self.log(
                            service_id,
                            "info",
                            &format!(
                                "Waiting for API... (attempt {attempt}/60, status: {})",
                                resp.status()
                            ),
                            "system",
                        )
                        .await
                        .ok();
                    }
                }
                Err(_) => {
                    if attempt % 10 == 0 {
                        self.log(
                            service_id,
                            "info",
                            &format!("Waiting for API... (attempt {attempt}/60, not reachable yet)"),
                            "system",
                        )
                        .await
                        .ok();
                    }
                }
            }
        }

        false
    }

    async fn log(
        &self,
        service_id: Uuid,
        level: &str,
        message: &str,
        source: &str,
    ) -> Result<(), AppError> {
        insert_and_broadcast_service_log(
            &self.pool,
            &self.service_log_broadcaster,
            service_id,
            level,
            message,
            source,
        )
        .await
    }

    async fn write_supabase_configs(&self, service_dir: &Path) -> Result<(), AppError> {
        // Create volumes directories that Supabase expects
        let volumes_dir = service_dir.join("volumes");
        for dir in &[
            "api",
            "db/init",
            "db/data",
            "storage",
            "functions",
        ] {
            tokio::fs::create_dir_all(volumes_dir.join(dir))
                .await
                .map_err(|e| {
                    AppError::Internal(format!("failed to create volume dir {dir}: {e}"))
                })?;
        }

        // Write Kong config
        let kong_yml = include_str!("templates/kong.yml");
        tokio::fs::write(volumes_dir.join("api/kong.yml"), kong_yml)
            .await
            .map_err(|e| AppError::Internal(format!("failed to write kong.yml: {e}")))?;

        Ok(())
    }
}

async fn insert_and_broadcast_service_log(
    pool: &sqlx::PgPool,
    broadcaster: &ServiceLogBroadcaster,
    service_id: Uuid,
    level: &str,
    message: &str,
    source: &str,
) -> Result<(), AppError> {
    let log = db_services::insert_log_returning(pool, service_id, level, message, source).await?;
    broadcaster
        .send(
            service_id,
            ServiceLogMessage {
                id: log.id,
                service_id: log.service_id,
                timestamp: log.timestamp,
                level: log.level,
                message: log.message,
                source: log.source,
            },
        )
        .await;
    Ok(())
}

fn generate_random_string(len: usize) -> String {
    let mut rng = rand::rng();
    let chars: Vec<char> = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        .chars()
        .collect();
    (0..len).map(|_| chars[rng.random_range(0..chars.len())]).collect()
}

fn generate_supabase_jwt(jwt_secret: &str, role: &str) -> String {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    let header = URL_SAFE_NO_PAD.encode(r#"{"alg":"HS256","typ":"JWT"}"#);

    // Expire in ~10 years
    let exp = chrono::Utc::now().timestamp() + 315_360_000;
    let payload_json = format!(
        r#"{{"role":"{role}","iss":"supabase","iat":{},"exp":{exp}}}"#,
        chrono::Utc::now().timestamp()
    );
    let payload = URL_SAFE_NO_PAD.encode(&payload_json);

    let unsigned = format!("{header}.{payload}");
    let mut mac =
        Hmac::<Sha256>::new_from_slice(jwt_secret.as_bytes()).expect("HMAC key length is valid");
    mac.update(unsigned.as_bytes());
    let signature = URL_SAFE_NO_PAD.encode(mac.finalize().into_bytes());

    format!("{unsigned}.{signature}")
}

fn generate_supabase_compose() -> String {
    r#"# Supabase Docker Compose (managed by Rift)
version: "3.8"

services:
  studio:
    image: supabase/studio:20240422-5cf8f30
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/profile', (r) => { if (r.statusCode !== 200) throw new Error(r.statusCode) })"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      analytics:
        condition: service_healthy
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION}
      DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT}
      SUPABASE_URL: ${API_EXTERNAL_URL}
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
    ports:
      - "${STUDIO_PORT}:3000"

  kong:
    image: kong:2.8.1
    restart: unless-stopped
    entrypoint: bash -c 'eval "echo \"$$(cat ~/temp.yml)\"" > ~/kong.yml && /docker-entrypoint.sh kong docker-start'
    ports:
      - "${KONG_HTTP_PORT}:8000/tcp"
    depends_on:
      analytics:
        condition: service_healthy
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
    volumes:
      - ./volumes/api/kong.yml:/home/kong/temp.yml:ro

  auth:
    image: supabase/gotrue:v2.151.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP}
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}
      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM}

  rest:
    image: postgrest/postgrest:v12.0.1
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: ${JWT_SECRET}
      PGRST_APP_SETTINGS_JWT_EXP: ${JWT_EXPIRY}
    command: "postgrest"

  realtime:
    image: supabase/realtime:v2.28.32
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sSfL", "--head", "-o", "/dev/null", "-H", "Authorization: Bearer ${ANON_KEY}", "http://localhost:4000/api/tenants/realtime-dev/health"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    environment:
      PORT: 4000
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: supabase_admin
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime'
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: ${JWT_SECRET}
      SECRET_KEY_BASE: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
      ERL_AFLAGS: -proto_dist inet_tcp
      DNS_NODES: "''"
      RLIMIT_NOFILE: "10000"
      APP_NAME: realtime
      SEED_SELF_HOST: "true"

  storage:
    image: supabase/storage-api:v1.0.6
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/status"]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      rest:
        condition: service_started
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: stub
      GLOBAL_S3_BUCKET: stub
      IS_MULTITENANT: "false"
    volumes:
      - ./volumes/storage:/var/lib/storage:z

  meta:
    image: supabase/postgres-meta:v0.80.0
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: ${POSTGRES_HOST}
      PG_META_DB_PORT: ${POSTGRES_PORT}
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}

  analytics:
    image: supabase/logflare:1.4.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4000/health"]
      timeout: 5s
      interval: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
    environment:
      LOGFLARE_NODE_HOST: 127.0.0.1
      DB_USERNAME: supabase_admin
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOSTNAME: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: _analytics
      LOGFLARE_API_KEY: ${SERVICE_ROLE_KEY}
      LOGFLARE_SINGLE_TENANT: "true"
      LOGFLARE_SUPABASE_MODE: "true"
      LOGFLARE_MIN_CLUSTER_SIZE: 1
      POSTGRES_BACKEND_URL: postgresql://supabase_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      POSTGRES_BACKEND_SCHEMA: _analytics
      LOGFLARE_FEATURE_FLAG_OVERRIDE: multibackend=true

  db:
    image: supabase/postgres:15.1.1.41
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres -h localhost
      timeout: 5s
      interval: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432/tcp"
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXPIRY}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data:Z
"#
    .to_string()
}
